disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Adrian Melian"

[params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    dateFormat = "2 January 2006"
    logo = "adrianmelian_logo_72px.png"
    secondaryLogo = "adrianmelian_logo_512px.png"
    description = "Adrian Melian - Technical Artst - Portfolio Site"

[params.author]
    name = "Adrian Melian"
    email = "AdrianMelian123@gmail.com"
    headline = "Technical Artist | Animator | Maker of Things"
    bio = "Adrian Melian is a Technical Artist and Animator with over 15 years of experience in the video game industry. He has worked on various high-profile projects, including Call of Duty, South Park, and Broken Age. Adrian is passionate about creating engaging and visually stunning experiences for players."
    image = "portrait_face.png"
    links = [
        { LinkedIn = "https://www.linkedin.com/in/adrian-melian-33066423" },
        { GitHub = "https://github.com/adrianmelian" },
        { YouTube = "https://www.youtube.com/@age914" },
    ]
